/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/dog.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.02, 5.06, 2.09]}>
        <group position={[5.04, 1.97, -2.09]}>
          <group position={[-4.4, -5.82, 2.08]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.foot_1.geometry}
              material={nodes.foot_1.material}
              position={[0.29, 0, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[0.8, 0.24, 0.8]}
            />
          </group>
          <group position={[-7.32, -1.5, 0.01]}>
            <group position={[2.28, -0.96, 0.46]} rotation={[Math.PI / 2, -0.13, 0]}>
              <group position={[0, 1.61, 0]} rotation={[Math.PI, -1.33, 1.57]} scale={[1, 1, 1]}>
                <group position={[0, 1.95, 0]} rotation={[2.06, 0, -Math.PI]}>
                  <group
                    position={[-0.33, -0.01, 0.01]}
                    rotation={[-1.58, 0, 1.57]}
                    scale={[0.41, 0.17, 0.41]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder017.geometry}
                      material={nodes.Cylinder017.material}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder017_1.geometry}
                      material={nodes.Cylinder017_1.material}
                    />
                  </group>
                </group>
                <group
                  position={[-0.01, 0.03, -0.38]}
                  rotation={[-1.55, 0, 0]}
                  scale={[0.39, 0.17, 0.39]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder012.geometry}
                    material={nodes.Cylinder012.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder012_1.geometry}
                    material={nodes.Cylinder012_1.material}
                  />
                </group>
              </group>
              <group
                position={[0.01, 1.62, 0.03]}
                rotation={[0, -0.26, -Math.PI / 2]}
                scale={[0.56, 0.24, 0.56]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder010.geometry}
                  material={nodes.Cylinder010.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder010_1.geometry}
                  material={nodes.Cylinder010_1.material}
                />
              </group>
            </group>
            <group position={[-2.71, -0.96, 0.46]} rotation={[Math.PI / 2, 0.47, 0]}>
              <group position={[0, 1.61, 0]} rotation={[0, -1.32, -1.57]} scale={[1, 1, 1]}>
                <group position={[0, 1.95, 0]} rotation={[-2.03, 0, Math.PI]}>
                  <group
                    position={[-0.33, -0.02, 0]}
                    rotation={[-1.56, 0, 1.57]}
                    scale={[0.41, 0.17, 0.41]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder020.geometry}
                      material={nodes.Cylinder020.material}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder020_1.geometry}
                      material={nodes.Cylinder020_1.material}
                    />
                  </group>
                </group>
                <group
                  position={[-0.01, 0.02, -0.34]}
                  rotation={[-1.57, 0, 0]}
                  scale={[0.39, 0.17, 0.39]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder021.geometry}
                    material={nodes.Cylinder021.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder021_1.geometry}
                    material={nodes.Cylinder021_1.material}
                  />
                </group>
              </group>
              <group
                position={[-0.01, 1.62, 0.03]}
                rotation={[0, 0.26, -Math.PI / 2]}
                scale={[0.56, 0.24, 0.56]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder022.geometry}
                  material={nodes.Cylinder022.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder022_1.geometry}
                  material={nodes.Cylinder022_1.material}
                />
              </group>
            </group>
            <group position={[2.28, -0.96, -0.45]} rotation={[-Math.PI / 2, -1.03, 0]}>
              <group position={[0, 1.61, 0]} rotation={[0, 0.24, 1.57]}>
                <group position={[0, 1.95, 0]} rotation={[2.11, 0, -Math.PI]}>
                  <group
                    position={[0.34, -0.01, 0.01]}
                    rotation={[1.57, 0, 1.57]}
                    scale={[-0.41, -0.17, -0.41]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder026.geometry}
                      material={nodes.Cylinder026.material}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder026_1.geometry}
                      material={nodes.Cylinder026_1.material}
                    />
                  </group>
                </group>
                <group
                  position={[0, 0.03, -0.38]}
                  rotation={[1.59, 0, 0]}
                  scale={[-0.39, -0.17, -0.39]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder027.geometry}
                    material={nodes.Cylinder027.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder027_1.geometry}
                    material={nodes.Cylinder027_1.material}
                  />
                </group>
              </group>
              <group
                position={[-0.03, 1.61, -0.01]}
                rotation={[-Math.PI, 1.31, -Math.PI / 2]}
                scale={[-0.56, -0.24, -0.56]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder028.geometry}
                  material={nodes.Cylinder028.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder028_1.geometry}
                  material={nodes.Cylinder028_1.material}
                />
              </group>
            </group>
            <group position={[-2.71, -0.96, -0.45]} rotation={[-Math.PI / 2, -1.56, 0]}>
              <group position={[0, 1.61, 0]} rotation={[0, -0.25, 1.57]}>
                <group position={[0, 1.95, 0]} rotation={[-2.12, 0, Math.PI]}>
                  <group
                    position={[0.31, -0.02, 0]}
                    rotation={[1.58, 0, 1.57]}
                    scale={[-0.41, -0.17, -0.41]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder025.geometry}
                      material={nodes.Cylinder025.material}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder025_1.geometry}
                      material={nodes.Cylinder025_1.material}
                    />
                  </group>
                </group>
                <group
                  position={[0.03, 0.02, -0.34]}
                  rotation={[1.57, 0, 0]}
                  scale={[-0.39, -0.17, -0.39]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder024.geometry}
                    material={nodes.Cylinder024.material}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder024_1.geometry}
                    material={nodes.Cylinder024_1.material}
                  />
                </group>
              </group>
              <group
                position={[-0.03, 1.64, 0.01]}
                rotation={[0, 1.31, Math.PI / 2]}
                scale={[-0.56, -0.24, -0.56]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder023.geometry}
                  material={nodes.Cylinder023.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder023_1.geometry}
                  material={nodes.Cylinder023_1.material}
                />
              </group>
            </group>
            <group position={[-2.7, -0.99, -0.01]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                material={nodes.Cylinder001.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_1.geometry}
                material={nodes.Cylinder001_1.material}
              />
            </group>
          </group>
          <group position={[-9.5, -5.82, 2.08]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.foot001_1.geometry}
              material={nodes.foot001_1.material}
              position={[0.29, 0.1, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[0.8, 0.24, 0.8]}
            />
          </group>
          <group position={[-5.9, -5.82, -2.06]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.foot003_1.geometry}
              material={nodes.foot003_1.material}
              position={[0.29, 0, 0.01]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[-0.8, -0.24, -0.8]}
            />
          </group>
          <group position={[-11, -5.82, -2.06]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.foot002_1.geometry}
              material={nodes.foot002_1.material}
              position={[0.29, 0.1, -0.02]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[-0.8, -0.24, -0.8]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dog.glb')
